apiVersion: v1
kind: Service
metadata:
  name: port
spec:
  type: NodePort
  selector:
    type: frontend
    matchLabels:
      app: real-estate
  ports:
  - name: http
    port: 80
    nodePort: 30080